name: binary-search-tree
version: 1.0.0.4

dependencies:
  - base

library:
  exposed-modules: BST
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: BSTSpec.hs
    source-dirs: test
    dependencies:
      - binary-search-tree
      - hspec
      - QuickCheck
