name: rna-transcription
version: 1.3.0.10

dependencies:
  - base

library:
  exposed-modules: DNA
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: DNASpec.hs
    source-dirs: test
    dependencies:
      - rna-transcription
      - hspec
