name: pascals-triangle
version: 1.5.0.9

dependencies:
  - base

library:
  exposed-modules: Triangle
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: TriangleSpec.hs
    source-dirs: test
    dependencies:
      - pascals-triangle
      - hspec
      - QuickCheck
