name: pangram
version: 2.0.0.12

dependencies:
  - base

library:
  exposed-modules: Pangram
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: PangramSpec.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
